### ISSUE TITLE
[User Story]: Make user story for Translation Academy

### ISSUE THREAD

**Issue by Valyukhov** [hiscoder-com/level#687]
Make description what we need for new tool.
How it will be look like.
What kind of navigation/buttons.
After making user story add task for designer.

Example -
https://docs.google.com/document/d/1pNHINabnSb6myGHOBvyKyI0lxvuHLgAmqXCXKMSzfn8/edit

**Comment by RussLangMan** [comment]
![Image](https://github.com/user-attachments/assets/030bc8cf-9115-4618-ac67-2bbef527b4a7)
