### ISSUE TITLE
[Design]:Make new sidebar

### ISSUE THREAD

**Issue by Valyukhov** [hiscoder-com/level#688]
We have example of sidebar from desktop version

![Image](https://github.com/user-attachments/assets/bc25eec3-5c5a-4a63-be00-781d8b2bcfe2)

Figma link:

https://www.figma.com/design/xQdOsk2RCupPhsR1pQ5Ddk/VCANA-DESK?node-id=6-466&t=L1GN2OnylDkFHtIx-4

We have sidebar in online version
![Image](https://github.com/user-attachments/assets/6e07e9a5-89f3-433c-97ca-502d0cb5483b)

What we need:
1. Make sidebar in online version like we made in desktop.
В верхней части сайдбара находятся:
- аватар пользователя.
под аватаром - никнейм и емайл
- Личный кабинет
- Проекты
- Создать проект
- Блокнот
- Управление пользователями
В середине:
- выбор темы

В нижней части:
- язык
- О нас (About)
- Версия
- Выйти

О нас - взять из десктопа
![Image](https://github.com/user-attachments/assets/31105565-3810-48e7-8f84-61a9267eb171)

**Comment by RussLangMan** [comment]
About the platform:

V-CANA is a contemporary Bible translation platform utilizing a variety of reference materials from our partners. The platform adapts to the unique translation methods of each mission and organization. 

V-CANA is available in three versions: online, intranet, and desktop. 

V-CANA provides a step-by-step translation process that produces clear, accurate and natural text in the target language. At each step, only the tools and materials needed for that stage of translation are available. This approach makes the translation process efficient and convenient. 

V-CANA is your trusted tool in creating quality and church-centered translations.



We'd like to hear from you:

- the problems you have encountered while using the platform;
- your suggestions for improving the platform and your requests for new features;
- testimonies about the usefulness of our platform and its impact on your project.


If you experience a problem write to us:

- describe the problem;
- if possible, attach a screenshot.


omg@v-cana.com

Thank you for using the V-CANA plaftorm!


V-CANA - made by translators for translators!

**Comment by RussLangMan** [comment]
О платформе:

V-CANA — это современная платформа для перевода Библии с использованием различных справочных материалов наших партнёров. Платформа адаптируется под уникальные методы переводов каждой миссии и организации. 

V-CANA доступна в трёх вариантах: онлайн, интранет и десктоп. 

V-CANA предоставляет пошаговый процесс перевода, который позволяет получить ясный, точный и естественный текст на целевом языке. На каждом этапе доступны только те инструменты и материалы, которые необходимы для данного этапа перевода. Такой подход делает процесс перевода эффективным и удобным. 

V-CANA — ваш надёжный инструмент в создании качественных и церквоориентированных переводов.


Мы бы хотели услышать от вас:

- о проблемах, с которыми вы столкнулись при использовании платформы;
- ваши предложения по улучшению платформы и ваши пожелания по новым функциям;
- свидетельства о пользе нашей платформы и ее влиянии на ваш проект.


Если вы столкнулись с проблемой, напишите нам:

- опишите проблему;
- по возможности приложите скриншот.

omg@v-cana.com

Благодарим вас за использование плафтормы V-CANA!


V-CANA — сделано переводчиками для переводчиков!

**Comment by RussLangMan** [comment]
Acerca de la plataforma:

V-CANA es una plataforma de traducción bíblica contemporánea que utiliza diversos materiales de referencia de nuestros socios. La plataforma se adapta a los métodos de traducción propios de cada misión y organización.

V-CANA está disponible en tres versiones: en línea, intranet y escritorio.

V-CANA ofrece un proceso de traducción paso a paso que produce un texto claro, preciso y natural en el idioma de destino. En cada paso, sólo están disponibles las herramientas y los materiales necesarios para esa fase de la traducción. Este enfoque hace que el proceso de traducción sea eficaz y cómodo.

V-CANA es su herramienta de confianza para crear traducciones de calidad y centradas en la iglesia.

Nos gustaría saber de usted

los problemas que ha encontrado al utilizar la plataforma;
sus sugerencias para mejorar la plataforma y sus peticiones de nuevas funciones;
testimonios sobre la utilidad de nuestra plataforma y su repercusión en su proyecto.
Si tiene algún problema, escríbanos:

describa el problema;
si es posible, adjunte una captura de pantalla.
omg@v-cana.com

Gracias por utilizar la plataforma V-CANA.

V-CANA - ¡hecho por traductores para traductores!

Traducción realizada con la versión gratuita del traductor DeepL.com

**Comment by Valyukhov** [comment]
@RussLangMan на доработку, есть изменнения в названии - Level
